name: 04 - Using Actions

on : workflow_dispatch

jobs: 
    build:
       runs-on: ubuntu-latest
    # whenever we run run command below 22 line that time working-directory will run so no need to run duplicate workig=ing direcotry
    #    defaults:
    #      run: 
    #        working-directory: 04-using-actions/react-app 
       steps:
        #  - name: Checkout
        #    uses: action/checkout@v4 , not using becase verion 4 is not available
        #  - name: Printig folders
        #    run: ls
         - name: Setup node 
           uses: actions/setup-node@v3
           with:
             node-version: "20.x"
         - name: Install Dependencies
           run: npm ci
           working-directory: 04-using-actions/react-app
        # Install dependencies step is not working because checkout is not happening

    #1 . Install dependencies for our react app
    #2 . Execute automated tests
