name: 05 - 1 - Event Filters and Activity Types

on:
  pull_request:
    # when type/PR is open or sync AND
    types:
        - opened
        - synchronize
    branches:
        - main
    # branch is main

jobs:
    echo:
      runs-on: ubuntu-latest
     
      steps:
          - run: echo "Running whenever a PR is opened or synchronized AND base branch is main"