name: 05 - 2 - Event Filters and Activity Types

on:
  pull_request:
    # when type/PR is closed or sync AND
    types:
        - closed
    branches:
        - main
    # branch is main

jobs:
    echo:
      runs-on: ubuntu-latest
     
      steps:
          - run: echo "Running whenever a PR is closed AND base branch is main"